from __future__ import annotations

import os
from pathlib import Path


def _int_value(value: object) -> int:
    if not isinstance(value, (int, float, str)):
        return 0
    try:
        return int(value)
    except (TypeError, ValueError):
        return 0


def netscape_domains(domain: str) -> list[tuple[str, str]]:
    trimmed = domain.strip()
    if not trimmed:
        return []
    if trimmed.startswith("."):
        return [(trimmed, "TRUE")]
    domains = [(trimmed, "FALSE")]
    if "." in trimmed and ":" not in trimmed:
        domains.append(("." + trimmed, "TRUE"))
    return domains


def netscape_cookie_text(cookies: list[dict[str, object]]) -> str:
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by OpenBBQ.",
    ]
    for cookie in cookies:
        name = str(cookie.get("name", "")).strip()
        value = str(cookie.get("value", ""))
        path = str(cookie.get("path", "") or "/")
        secure = "TRUE" if cookie.get("secure") else "FALSE"
        expires = str(_int_value(cookie.get("expires", 0)))
        if not name or not value:
            continue
        for domain, include_subdomains in netscape_domains(str(cookie.get("domain", ""))):
            lines.append(
                "\t".join(
                    [domain, include_subdomains, path, secure, expires, name, value]
                )
            )
    return "\n".join(lines) + "\n"


def write_netscape(path: Path, cookies: list[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name("." + path.name + ".tmp")
    tmp.write_text(netscape_cookie_text(cookies), encoding="utf-8")
    os.chmod(tmp, 0o600)
    os.replace(tmp, path)
